### ISSUE TITLE
Control syncthing daemon executable from tray action

### ISSUE THREAD

**Issue by xor-gate** [syncthing/syncthing-macos#48]
Currently it is not possible to control the syncthing subprocess with start/stop/restart actions. Also we must sure we don't lose track of the subprocess.

**Comment by ngocphamm** [comment]
I think I'm having an issue related to this, when I use ControlPlane to "switch context" for my laptop. Upon leaving a context, I would have ControlPlane to "quit" the app. I don't really know what signal it sends to "quit" the app, but I noticed for now it seems to just "kill" the main app process `Syncthing` (first letter capitalized), and the sub-processes of `syncthing` are still there.

Would love to see this being implemented. Please let me know if I can do some testing because I'm afraid I can't help with the actual development :(

**Comment by xor-gate** [comment]
Yes I have also observed this bug, the wrapper sometimes loses track of the running `syncthing` subprocess. I need some more time on this. Currently I'm working in my free time on #54. Thanks for reporting, highly appreciated!

**Comment by ngocphamm** [comment]
Not a problem! I'm thankful for people like you who work on open-source projects for the sake of many others. Just let me know if I can help with testing!

**Comment by xor-gate** [comment]
As soon there is some progress you get notified in this issue.

**Comment by calmh** [comment]
So currently it's a fairly fire-and-forget sort of setup. If Syncthing doesn't launch we'll never know, if we crash it'll stay running in the background, and it uses the standard monitoring process for restarts etc. I think we should do the work of the Syncthing monitor process ourselves here and manage restarts etc., and make visible the daemon state somehow in the UI.

The one abnormality that I think would be worth handling is if Syncthing exits or can't be started, yet is reachable via the API. This happens if it's already running in the background for example - we can't start it *again*, but we can talk to it. This should be a success scenario, and when we can no longer talk to it over the API we should try starting it again. (Or maybe try starting it periodically regardless.)

I can try to tackle this is noone objects.

**Comment by xor-gate** [comment]
Yes this is indeed FAF. Because I initialy started the project for personal use it worked fairly well. But those corner cases where stuff is not working should be handled in a convient way. When putting it out in the wild and more people going to actual install it on their computer.

**Comment by xor-gate** [comment]
Fixed in #71
